### PR TITLE
Only do ACM cert validation if ACM is actually in use

### LINKED ISSUE #7: ACM certificate error following update
```
Error: Invalid index
│
│   on .terraform/modules/teleport-cluster-terraform/acm.tf line 22, in resource "aws_route53_record" "cert_validation":
│   22:     for dvo in aws_acm_certificate.cert[0].domain_validation_options : dvo.domain_name => {
│     ├────────────────
│     │ aws_acm_certificate.cert is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```

This shouldn't happen when `use_acm` is false.

### PR DESCRIPTION
**Pull request by webvictim**
This was an oversight introduced in #5

Fixes #7

### CODE REVIEW

**Comment by dilchenko** [comment]
When I tried to fix #7, I am fairly certain this did not fix it. Did you try to run a plan with both am enabled and disabled?

**Comment by gozer** [comment]
Usage of `aws_route53_record.cert_validation` needs to become `aws_route53_record.cert_validation[0]`

**Comment by webvictim** [comment]
I haven't tried to plan anything, this was reported by a customer who's using the module and found that things broke.

I'll see if I can get a sample setup going later.

**Comment by gozer** [comment]
> When I tried to fix #7, I am fairly certain this did not fix it. Did you try to run a plan with both am enabled and disabled?

744446c should fix that

**Review by gozer — APPROVED** [review]

**Review by evanfreed — APPROVED** [review]

**Pull request merged**
